require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/**/*.rb'
