# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use SCIM v2.0
gem 'scimitar', '~> 2.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'database_consistency', require: false
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'faker', '~> 3.1.1'
  gem 'fuubar', '~> 2.5.1', require: false
end

group :development do
  gem 'annotate', '~> 3.2.0'
  gem 'rubocop', '~> 1.49', require: false
  gem 'rubocop-performance', '~> 1.16.0', require: false
  gem 'rubocop-rails', '~> 2.18.0', require: false
  gem 'rubocop-rspec', '~> 2.19.0', require: false
  gem 'solargraph', '~> 0.48.0'
  gem 'solargraph-rails', '~> 1.1.0'
end

group :test do
  gem 'n_plus_one_control', '~> 0.7.1', require: false
  gem 'rspec-rails', '~> 6.0.1', require: false
  gem 'test-prof', '~> 1.0.0'
end
